import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {MetricsClient,type MetricsFetch} from '../src/platform/metrics';
const ok=()=>new Response(JSON.stringify({ok:true}),{status:200});
const store=(saved:string|null=null):Storage=>{let value=saved;return {getItem:()=>value,setItem:(_:string,v:string)=>{value=v},removeItem:()=>{value=null},clear:()=>{value=null},key:()=>null,length:0} as Storage};
const flush=async()=>{for(let i=0;i<10;i++)await Promise.resolve();try{await vi.advanceTimersByTimeAsync(0)}catch{}};
let uuid=0;beforeEach(()=>{uuid=0;vi.stubGlobal('crypto',{randomUUID:()=>`00000000-0000-4000-8000-${String(++uuid).padStart(12,'0')}`})});afterEach(()=>{vi.useRealTimers();vi.unstubAllGlobals()});
describe('MetricsClient presence reporter',()=>{
 it('reuses installation UUID and creates a new session UUID',async()=>{const b:Record<string,unknown>[]=[];const fetch=vi.fn(async(_:RequestInfo|URL,i?:RequestInit)=>{if(i?.body)b.push(JSON.parse(String(i.body)));return ok()});new MetricsClient({baseURL:'https://qa',storage:store(),fetch}).start();await flush();new MetricsClient({baseURL:'https://qa',storage:store(String(b[0]?.installationId)),fetch}).start();await flush();expect(b[1].installationId).toBe(b[0].installationId);expect(b[1].sessionId).not.toBe(b[0].sessionId)});
 it('coalesces 100 identical active calls and sends one heartbeat',async()=>{vi.useFakeTimers();const b:Record<string,unknown>[]=[];const fetch=vi.fn(async(_:RequestInfo|URL,i?:RequestInit)=>{if(i?.body)b.push(JSON.parse(String(i.body)));return ok()});const c=new MetricsClient({baseURL:'https://qa',storage:store(),fetch});c.start();await flush();for(let i=0;i<100;i++)c.setActive(true);await flush();expect(b).toHaveLength(2);await vi.advanceTimersByTimeAsync(30_000);await flush();expect(b).toHaveLength(3)});
 it('does not network or write when report is disabled or storage denied',async()=>{const writes:string[]=[];const denied={getItem:()=>{throw Error()},setItem:(_:string,v:string)=>writes.push(v)} as unknown as Storage;const fetch=vi.fn(async()=>ok());new MetricsClient({baseURL:'https://qa',report:false,storage:denied,fetch}).start();await flush();new MetricsClient({baseURL:'https://qa',storage:denied,fetch}).start();await flush();expect(fetch).not.toHaveBeenCalled();expect(writes).toHaveLength(0)});
 it('sends inactive keepalive in background and active on resume',async()=>{const b:Record<string,unknown>[]=[];const inits:RequestInit[]=[];const fetch=vi.fn(async(_:RequestInfo|URL,i?:RequestInit)=>{if(i?.body){inits.push(i);b.push(JSON.parse(String(i.body)))}return ok()});const c=new MetricsClient({baseURL:'https://qa',storage:store(),fetch});c.start();c.setActive(true);await flush();c.setForeground(false);await flush();expect(b.at(-1)?.active).toBe(false);expect(inits.at(-1)?.keepalive).toBe(true);c.setForeground(true);await flush();expect(b.at(-1)?.active).toBe(true)});
 it('retries failed initial inactive registration after 30 seconds',async()=>{vi.useFakeTimers();let n=0;const b:Record<string,unknown>[]=[];const fetch=vi.fn(async(_:RequestInfo|URL,i?:RequestInit)=>{if(i?.body){n++;b.push(JSON.parse(String(i.body)));return n===1?new Response('',{status:503}):ok()}return ok()});new MetricsClient({baseURL:'https://qa',storage:store(),fetch}).start();await flush();await vi.advanceTimersByTimeAsync(30_000);await flush();expect(n).toBe(2);expect(b[1].active).toBe(false)});
 it('aborts unresolved fetch and JSON after 8 seconds',async()=>{vi.useFakeTimers();let signal:AbortSignal|undefined;const hanging={ok:true,json:()=>new Promise<unknown>(()=>{})} as unknown as Response;const fetch:MetricsFetch=vi.fn((_:RequestInfo|URL,i?:RequestInit)=>{signal=i?.signal??undefined;return Promise.resolve(hanging)});new MetricsClient({baseURL:'https://qa',storage:store(),fetch}).start();await vi.advanceTimersByTimeAsync(8_000);expect(signal?.aborted).toBe(true)});
 it('ignores late response after shutdown and leaves no timers',async()=>{vi.useFakeTimers();let resolve!: (r:Response)=>void;const pending=new Promise<Response>(r=>{resolve=r});const fetch=vi.fn((_:RequestInfo|URL,i?:RequestInit)=>i?.method==='POST'?pending:Promise.reject(Error()));const c=new MetricsClient({baseURL:'https://qa',storage:store(),fetch});c.start();c.shutdown();resolve(ok());await flush();await vi.advanceTimersByTimeAsync(60_000);expect(vi.getTimerCount()).toBe(0);c.setActive(true);c.setForeground(true);expect(fetch).toHaveBeenCalledTimes(2)});
});
