import {describe,it,expect} from 'vitest';
import {Simulation, freshSave, actor} from '../src/game/sim';
import {POINTS} from '../src/game/config';
import {validateSave,persist,load,SAVE_KEY} from '../src/game/save';
function advance(g:Simulation,seconds:number){for(let i=0;i<Math.round(seconds*30);i++)g.step(1/30);}
function rich(){const g=new Simulation();g.s.coins=10000;return g;}
describe('café causal rules',()=>{
 it('starts with no employees and no unattended coffee',()=>{const g=new Simulation();advance(g,12);expect(g.b.ready).toHaveLength(0);expect(g.s.player.cups).toHaveLength(0);expect(Object.keys(g.b.workers)).toHaveLength(0);});
 it('produces a seated guest’s real coffee at the machine, using a bean',()=>{const g=new Simulation();g.b.spawn=100;g.b.customers=[{...actor(g.seatPoint(0)),id:1,kind:'espresso',seat:0,state:'waiting',patience:70,maxPatience:70,timer:0,paid:false,tint:0}];g.s.player=actor(POINTS.machine);const stock=g.b.stock;advance(g,5);expect(g.s.player.cups.length).toBeGreaterThan(0);expect(g.b.stock).toBeLessThan(stock);});
 it('new table doubles real capacity and refuses purchases without funds',()=>{const g=new Simulation();expect(g.upgrade('table')).toBe(false);g.s.coins=g.price('table');expect(g.upgrade('table')).toBe(true);expect(g.b.level.table*2).toBe(4);expect(g.s.coins).toBe(0);});
 it('machine upgrade reduces actual brew duration',()=>{const g=rich(),old=g.brewTime;g.upgrade('machine');expect(g.brewTime).toBeLessThan(old*.8);});
 it('stock cannot go negative and empty stock blocks production',()=>{const g=new Simulation();g.s.player=actor(POINTS.machine);g.b.stock=0;advance(g,12);expect(g.s.player.cups).toHaveLength(0);expect(g.b.stock).toBe(0);});
 it('free supply recovers an empty café',()=>{const g=new Simulation();g.b.stock=0;g.s.player=actor(POINTS.supply);advance(g,2);expect(g.s.player.cargo?.beans).toBe(8);g.s.player.x=POINTS.machine.x;g.s.player.z=POINTS.machine.z;advance(g,1);expect(g.b.stock).toBe(8);expect(g.s.player.beans).toBe(0);});
 it('guests leave and the cause is attributed when service fails',()=>{const g=new Simulation();const startingRating=g.b.rating;g.s.totalServed=3;advance(g,110);expect(g.b.lost).toBeGreaterThan(0);expect(g.b.losses.service+g.b.losses.seat).toBeGreaterThan(0);expect(g.b.rating).toBeLessThan(startingRating);});
 it('unserved prepared coffee spoils',()=>{const g=new Simulation();g.b.ready.push({kind:'espresso',quality:0,born:0});advance(g,37);expect(g.b.waste).toBe(1);expect(g.b.ready).toHaveLength(0);});
 it('five hired workers run actual production, service and supply while player rests',()=>{const g=rich();g.hire('barista');g.hire('waiter');g.hire('supplier');g.hire('cleaner');g.hire('dishwasher');g.s.player=actor({x:0,z:5.8});const start=g.s.coins;advance(g,240);expect(g.b.served).toBeGreaterThan(6);expect(g.s.coins).toBeGreaterThan(start);expect(g.b.stock).toBeGreaterThan(0);expect(g.b.workers.waiter!.x).not.toBe(-.6);});
 it('menu switch preserves existing orders and remains fulfillable',()=>{const g=rich();g.hire('barista');g.hire('waiter');g.hire('supplier');advance(g,20);g.setMenu('latte');advance(g,150);expect(g.b.served).toBeGreaterThan(3);expect(g.b.brewing).toBe('latte');});
 it('reward callback is idempotent',()=>{const g=new Simulation(),start=g.s.coins;expect(g.reward('one','coins')).toBe(true);expect(g.reward('one','coins')).toBe(false);expect(g.s.coins).toBe(start+500);});
 it('offline is capped, requires automation, and cannot be claimed twice',()=>{const g=rich();g.s.savedAt=1000;expect(g.offline(7201000,true).amount).toBe(0);g.hire('barista');g.hire('waiter');g.hire('supplier');g.hire('cleaner');g.hire('dishwasher');g.s.savedAt=1000;const first=g.offline(86401000,true);expect(first.seconds).toBe(14400);expect(first.amount).toBeGreaterThan(0);expect(g.offline(86401000,true).amount).toBe(0);});
 it('branch unlock spends actual funds and retains old business',()=>{const g=rich();const before=g.s.coins;g.b.mastery=1;g.b.level.machine=3;expect(g.switchBranch(1)).toBe(true);expect(g.s.coins).toBe(before-4500);expect(g.b.level.machine).toBe(1);expect(g.switchBranch(0)).toBe(true);expect(g.b.level.machine).toBe(3);expect(g.switchBranch(99)).toBe(false);});
 it('validates a long-running save and rejects malformed data',()=>{const g=rich();Object.keys(g.b.staff).forEach(r=>g.hire(r as 'barista'));advance(g,180);expect(validateSave(g.s)).toBe(true);const bad=structuredClone(g.s);bad.player.x=NaN;expect(validateSave(bad)).toBe(false);expect(validateSave({version:1})).toBe(false);});
 it('recovers a backup and retains the only corrupt source',()=>{const values=new Map<string,string>();const storage={getItem:(k:string)=>values.get(k)??null,setItem:(k:string,v:string)=>{values.set(k,v);},removeItem:(k:string)=>{values.delete(k);}};const s=freshSave();expect(persist(s,storage)).toBe(true);s.coins=100;persist(s,storage);storage.setItem(SAVE_KEY,'{broken');expect(load(storage).status).toBe('recovered');values.clear();storage.setItem(SAVE_KEY,'{broken');expect(load(storage).status).toBe('corrupt');expect(storage.getItem(SAVE_KEY+'.corrupt')).toBe('{broken');});
});
