import {MENU,STAFF,UPGRADES,INGREDIENTS,type Menu,type Role,type Upgrade} from '../game/config';
import {TABLE_TYPES} from '../game/table-layout';
import {diamondPrice,type Purchase} from '../game/diamonds';
import {PRICING} from '../game/pricing';
import {PERSONAS,REASONS} from '../game/guests';
import {DECOR,type DecorId} from '../game/decor';
import {type Simulation} from '../game/sim';
import {t,number,decimal} from '../game/i18n';
import {icon} from '../view/icons';
export type InvestmentCategory='space'|'equipment'|'products'|'team'|'decor';
export type {Purchase} from '../game/diamonds';
const money=(n:number)=>`${icon('coin')} ${number(n)}`;
export const categories:Record<InvestmentCategory,string>={space:'Kafeyi büyüt',equipment:'Ekipman',products:'Ürünler',team:'Çalışanlar',decor:'Dekor ve müzik'};
export function purchaseInfo(g:Simulation,p:Purchase){return {...basePurchaseInfo(g,p),diamondCost:diamondPrice(g,p)};}
function basePurchaseInfo(g:Simulation,p:Purchase){
 if(p.kind==='table-type'){const i=Number(p.id),current=g.tableCapacity(i),next=TABLE_TYPES[Math.min(3,g.b.tableLevels[i]+1)];return {title:`${t('Masa')} ${i+1} · ${t(next.name)}`,description:(next.space>g.b.level.space?`${t('Gereken alan seviyesi')}: ${next.space}. ${t('Önce kafeyi genişlet')}. `:'')+t('Rahat oturma müşterinin sabrını ve değerlendirmesini iyileştirir.'),price:g.tableUpgradePrice(i),effect:`${t('Koltuk')}: ${current} → ${next.seats} · ${t('Toplam kapasite')}: ${g.seatingCapacity} → ${g.seatingCapacity-current+next.seats} · ${t('Rahatlık / ek sabır')}: +${g.tableComfort(i)}s → +${next.comfort}s`,available:g.canUpgradeTable(i)};}
 if(p.kind==='recipe'){const k=p.id as Menu,m=MENU[k],l=g.b.catalog[k];return {title:t(m.name),description:t(l?'Tarifini geliştir, her satıştan daha çok kazan.':'Bu ürün menüne eklenir. Diğer ürünler de satılmaya devam eder.'),price:g.recipeUpgradeCost(k),effect:l?`${t('Satış')}: ${g.recipePrice(k)} → ${Math.round(m.price*(1+l*.1)*PRICING[g.b.priceModes[k]].price)}`:`${t(m.category)} · ${t('Satış')}: ${m.price} · ${m.brew}s`,available:l<3};}
 if(p.kind==='helper'){const k=p.id as Role;return {title:`${t('Yeni çalışan')} · ${t(STAFF[k].name)}`,description:t('Yeni bir çalışan aynı işi paylaşır. Eğitim seviyesi tüm rol için geçerlidir.'),price:g.additionalStaffPrice(k),effect:`${t('Çalışan sayısı')}: ${g.staffCount(k)} → ${g.staffCount(k)+1}`,available:g.staffCount(k)<g.staffLimit(k)&&g.b.staff[k]>0};}
 if(p.kind==='staff'){const k=p.id as Role,m=STAFF[k],l=g.b.staff[k];return {title:`${m.person} · ${t(m.name)}`,description:t(m.description),price:g.staffPrice(k),effect:l?`${t('Tüm rolü eğit')}: ${t('Seviye')} ${l} → ${l+1} · ${t('Yürüme hızı')} +22%${k==='barista'?` · ${t('Üretim hızı')} +18%`:k==='cleaner'||k==='dishwasher'?` · ${t('İş hızı')} +25%`:''}`:`${t('İşe al')}: ${t(m.name)}`,available:l<3};}
 if(p.kind==='decor'){const m=DECOR[p.id as DecorId];return {title:t(m.name),description:t(m.description),price:m.cost,effect:t('Kalıcı dekorasyon'),available:!g.b.decor.owned.includes(p.id as DecorId)};}
 const k=p.id as Upgrade,m=UPGRADES[k],l=g.b.level[k],cap=g.upgradeCap(k);
 const effects:Record<Upgrade,string>={speakers:t('Çalma listesi açılır; başlangıç ses düzeyi: düşük.'),stage:t('Gerçek müzisyenler ve canlı müzik; başlangıç sesi düşük.'),soundproof:t('Dışarı taşan müzik −24%, içerideki gürültü −10 puan.'),space:`${t('Masa için yer')}: ${g.maxTables} → ${Math.min(6,g.maxTables+2)}`,table:`${t('Koltuk')}: ${g.seatingCapacity} → ${g.seatingCapacity+2}`,machine:`${t('Hazırlık')}: ${decimal(g.brewTime)}s → ${decimal(g.brewTime*(1+(l-1)*.38)/(1+l*.38))}s`,tray:`${t('Tepsi')}: ${l} → ${l+1}`,quality:`${t('Satış kazancı')}: +15%`,stock:`${t('Çekirdek kapasitesi')}: ${g.stockCap} → ${g.stockCap+12}`,storage:`${t('Depo kapasitesi')}: ${g.depotCap} → ${g.depotCap+20}`,wash:`${t('Yıkama')}: ${decimal(2.2/(1+l*.35))}s → ${decimal(2.2/(1+(l+1)*.35))}s`};
 return {title:t(m.name),description:t(m.description),price:g.price(k),effect:effects[k],available:l<cap};
}
export function purchaseCard(g:Simulation,p:Purchase){const info=purchaseInfo(g,p);const needsSpace=p.kind==='upgrade'&&p.id==='table'&&!info.available&&g.b.level.space<g.maxSpace;if(needsSpace)return `<article class="investment-locked">${icon('chair')}<div><strong>${info.title}</strong><p>${t('Önce alanı genişlet. Yeni masalar ayrıca satın alınır.')}</p></div></article>`;const image=p.kind==='recipe'?`<img src="/menu-${p.id}.svg" alt="">`:icon(p.kind==='staff'||p.kind==='helper'?'team':p.kind==='decor'?DECOR[p.id as DecorId].icon:p.kind==='table-type'?'chair':UPGRADES[p.id as Upgrade].icon);return `<article class="investment-card"><div class="investment-illustration">${image}</div><div><h3>${info.title}</h3><p>${info.description}</p><strong class="investment-effect">${info.available?info.effect:t('Tamamlandı')}</strong></div><button class="primary" data-review-kind="${p.kind}" data-review-id="${p.id}" ${!info.available?'disabled':''}>${info.available?`${t('İncele')} · ${money(info.price)}`:t('Tamamlandı')}</button>${info.available&&g.s.coins<info.price?`<small>${t('Eksik')}: ${number(info.price-g.s.coins)}</small>`:''}</article>`;}
function teamPanel(g:Simulation){return `<p class="sheet-intro">${t('Eğitim tüm çalışanlara uygulanır; yeni çalışan ayrı bir kişidir.')}</p><div class="team-summary">${Object.entries(STAFF).map(([id,m])=>`<a href="#staff-${id}"><strong>${t(m.name)}</strong><span>${g.staffCount(id as Role)} / ${g.staffLimit(id as Role)}</span></a>`).join('')}</div><div class="staff-list">${Object.entries(STAFF).map(([id,m])=>{const role=id as Role,count=g.staffCount(role),level=g.b.staff[role];return `<article class="staff-card" id="staff-${id}"><div class="staff-heading">${icon('team')}<div><h3>${t(m.name)}</h3><small>${t('Çalışan sayısı')}: ${count}/${g.staffLimit(role)} · ${t('Eğitim')}: ${level}/3</small></div></div><p>${t(m.description)}</p><div class="staff-actions"><button data-review-kind="staff" data-review-id="${id}" ${level>=3?'disabled':''}>${t(!count?'İlk çalışanı işe al':level>=3?'Eğitim tamamlandı':'Tüm rolü eğit')}${level<3?` · ${money(g.staffPrice(role))}`:''}</button>${count?`<button data-review-kind="helper" data-review-id="${id}" ${count>=g.staffLimit(role)?'disabled':''}>${t(count>=g.staffLimit(role)?'Ekip tamam':'Bir çalışan daha')}${count<g.staffLimit(role)?` · ${money(g.additionalStaffPrice(role))}`:''}</button>`:''}</div></article>`;}).join('')}</div>`;}
function decorInvestments(g:Simulation){
 const slots=['floor','furniture','plants'] as const;
 return `<p class="sheet-intro">${t('Her kategoriden bir stil kullanılır. Konfor, seçili mobilya ve bitkilerden gelir.')}</p><button class="link-button" data-panel="decor">${t('Sahip olduğum dekorlar')}</button>`+slots.map((slot,index)=>{
  const ids=(Object.keys(DECOR) as DecorId[]).filter(id=>DECOR[id].slot===slot&&!g.b.decor.owned.includes(id));
  return ids.length?`<section class="decor-section"><h3>${t(['Zemin','Mobilya','Bitkiler'][index])}</h3><div class="investment-grid">${ids.map(id=>purchaseCard(g,{kind:'decor',id})).join('')}</div></section>`:'';
 }).join('')+`<h3>${t('Kafe müziğini yönet')}</h3><div class="investment-grid">${['speakers','stage','soundproof'].map(id=>purchaseCard(g,{kind:'upgrade',id})).join('')}</div>`;
}
export function investmentPanel(g:Simulation,category:InvestmentCategory){
 const symbols:Record<InvestmentCategory,string>={space:'grow',equipment:'coffee',products:'menu',team:'team',decor:'music'};
 const tabs=`<div class="investment-tabs" role="group" aria-label="${t('Yatırım bölümleri')}">${Object.entries(categories).map(([id,name])=>`<button data-invest="${id}" aria-label="${t(name)}" title="${t(name)}" aria-pressed="${category===id}" class="${category===id?'selected':''}">${icon(symbols[id as InvestmentCategory])}<span>${t(name)}</span></button>`).join('')}</div>`;
 const purchases:Purchase[]=category==='space'?['space','table'].map(id=>({kind:'upgrade',id})):category==='equipment'?['machine','tray','quality','stock','storage','wash'].map(id=>({kind:'upgrade',id})):category==='products'?Object.keys(MENU).map(id=>({kind:'recipe',id})):category==='team'?Object.keys(STAFF).map(id=>({kind:'staff',id})):[...['speakers','stage','soundproof'].map(id=>({kind:'upgrade' as const,id})),...Object.keys(DECOR).filter(id=>!g.b.decor.owned.includes(id as DecorId)).map(id=>({kind:'decor' as const,id}))];
 return `<p class="investment-wallet"><span>${t('Yatırım bütçen')}:</span><strong class="investment-balance">${money(g.s.coins)}</strong></p>${tabs}<h3 class="category-heading">${t(categories[category])}</h3>${category==='team'?teamPanel(g):category==='decor'?decorInvestments(g):category==='space'?`${tableTypesPanel(g)}<h3 id="floor-investments" class="floor-investments-title">${t('Alan ve yeni masalar')}</h3><div class="investment-grid">${purchases.map(p=>purchaseCard(g,p)).join('')}</div>`:`<div class="investment-grid">${purchases.map(p=>purchaseCard(g,p)).join('')}</div>`}${category==='decor'?`<button class="primary" data-panel="music">${t('Kafe müziğini yönet')}</button><button class="link-button" data-panel="decor">${t('Sahip olduğum dekorlar')}</button>`:''}`;
}
export function inventoryPanel(g:Simulation){return `<p class="sheet-intro">${t('Depodan malzemeleri al, hazırlık tezgâhına taşı. Teslimatlar ücretsizdir.')}</p><div class="stock-table"><div class="stock-row heading"><span>${t('Malzeme')}</span><span>${t('Tezgâh')}</span><span>${t('Depo')}</span></div>${Object.entries(INGREDIENTS).map(([key,name])=>`<div class="stock-row"><strong>${t(name)}</strong><span>${g.ingredient(key as keyof typeof INGREDIENTS)} / ${key==='beans'?g.stockCap:g.ingredientCap}</span><span>${g.b.depot[key as keyof typeof INGREDIENTS]} / ${g.depotCap}</span></div>`).join('')}</div><p>${t('Sonraki ücretsiz teslimat')}: ${Math.ceil(g.b.deliveryIn)}s</p><button data-storage-go class="primary">${t('Depodan malzeme al')}</button><div class="note"><h3>${t('Fincan döngüsü')}</h3><p>${t('Temiz')}: ${g.b.cleanDishes} · ${t('Yıkanacak')}: ${g.b.dirtyDishes} · ${t('Masada')}: ${Object.values(g.b.dirtyTables).reduce((n,v)=>n+v,0)}</p><button data-wash-go class="link-button">${t('Yıkama alanına git')}</button></div><button data-invest="equipment" class="link-button">${t('Depo ve ekipman yatırımları')}</button>`;}
export function menuPanel(g:Simulation){return `<div class="note"><h3>${t('Birlikte satışta')}: ${g.b.offered.length} / ${Object.values(g.b.catalog).filter(v=>v>0).length}</h3><p>${t('Birden fazla ürün açık kalabilir. Misafirler açık ürünler arasından seçer.')}</p></div><p class="sheet-intro">${t('Her ürünün fiyatını ayrı seç. Ucuz fiyat talebi artırır; yüksek fiyat satış başına kazancı artırır, talebi azaltır. Yeni fiyat yalnızca yeni siparişlere uygulanır.')}</p><div class="priced-menu">${Object.entries(MENU).filter(([k])=>g.b.catalog[k as Menu]>0).map(([k,m])=>{const key=k as Menu,active=g.b.offered.includes(key),locked=g.b.special?.status==='active'&&g.b.special.kind===key,mode=g.b.priceModes[key];return `<article class="priced-product"><div class="product-heading"><img src="/menu-${k}.svg" alt=""><div><h3>${t(m.name)}</h3><small>${t(m.category)} · ${decimal(m.brew)}s</small><strong>${t('Satış fiyatı')}: ${money(g.recipePrice(key))}</strong></div></div><button data-menu="${k}" aria-pressed="${active}" ${locked?'aria-disabled="true"':''} class="product-sale-toggle ${active?'active':''}">${t(locked?'Özel sipariş bitene kadar açık':active?'Satışta':'Menüde kapalı')}</button><fieldset class="product-prices"><legend>${t('Fiyat tercihi')}</legend><div>${Object.entries(PRICING).map(([id,pricing])=>`<button data-price-product="${k}" data-price-mode="${id}" aria-pressed="${mode===id}" class="${mode===id?'active':''}"><span>${t(pricing.name)}</span><strong>${money(Math.round(m.price*(1+Math.max(0,g.b.catalog[key]-1)*.1)*pricing.price))}</strong><small>${t('Talep')}: ${Math.round(pricing.demand*100)}%</small></button>`).join('')}</div></fieldset></article>`;}).join('')}</div><button data-invest="products" class="primary menu-expand">${t('Yeni ürün aç veya tarif geliştir')}</button><div class="setting-block"><h3>${t('Hazır ürün rafı sınırı')}</h3><p>${t('Yalnızca oturmuş misafirlerin siparişleri hazırlanır. Rafta en fazla bu kadar ürün bekler; fazla bekleyen ürün tazeliğini kaybeder.')}</p><div class="segments">${[1,3,5].map(n=>`<button data-prep="${n}" aria-pressed="${g.b.prep===n}" class="${g.b.prep===n?'active':''}">${n}</button>`).join('')}</div></div>`;}
export function furnitureThumbnail(level:number){
 const chair=(x:number,y:number,angle=0,cream=false)=>`<g class="thumb-armchair" transform="translate(${x} ${y}) rotate(${angle})"><rect x="-11" y="-12" width="22" height="25" rx="6" fill="${cream?'#d8cbb0':'#88a28a'}" stroke="#647963" stroke-width="1.4"/><rect x="-7" y="-7" width="14" height="16" rx="4" fill="${cream?'#f3e8d0':'#d8cbb0'}"/><path d="M-9-6V9M9-6V9M-7-9H7" fill="none" stroke="${cream?'#c5b797':'#a8ba9f'}" stroke-width="4" stroke-linecap="round"/></g>`;
 const coffee=(x:number,y:number,round=false)=>`<g class="thumb-coffee-table">${round?`<circle cx="${x}" cy="${y}" r="15" fill="#c99257" stroke="#966033" stroke-width="2"/>`:`<rect x="${x-12}" y="${y-9}" width="24" height="18" rx="5" fill="#c99257" stroke="#966033" stroke-width="2"/>`}<circle cx="${x+3}" cy="${y-2}" r="4" fill="#fff4d8"/><circle cx="${x+3}" cy="${y-2}" r="2" fill="#714832"/></g>`;
 const sofa=(salon:boolean)=>`<g class="thumb-l-sofa"><path d="${salon?'M9 11H98Q102 11 102 15V31H31V77Q31 81 27 81H9Q5 81 5 77V15Q5 11 9 11Z':'M18 18H77Q81 18 81 22V39H38V77Q38 81 34 81H18Q14 81 14 77V22Q14 18 18 18Z'}" fill="${salon?'#75988d':'#b97e67'}" stroke="${salon?'#506c62':'#855b45'}" stroke-width="2"/>${(salon?[38,70]:[46]).map(x=>`<rect x="${x}" y="${salon?16:23}" width="${salon?26:28}" height="15" rx="3" fill="${salon?'#b4c7b8':'#e0b69b'}"/>`).join('')}${(salon?[25,43,61]:[42,61]).map(y=>`<rect x="${salon?11:20}" y="${y}" width="${salon?18:17}" height="16" rx="3" fill="${salon?'#b4c7b8':'#e0b69b'}"/>`).join('')}</g>`;
 const art=level===0?`<g class="thumb-bistro"><rect x="29" y="40" width="14" height="21" rx="3" fill="#afbd83" stroke="#687c49" stroke-width="2"/><rect x="85" y="40" width="14" height="21" rx="3" fill="#afbd83" stroke="#687c49" stroke-width="2"/>${coffee(64,50,true)}</g>`:level===1?`${chair(64,18)}${chair(31,53,-90)}${chair(97,53,90)}${chair(64,87,180)}${coffee(64,53)}`:level===2?`${sofa(false)}${chair(103,42,90,true)}${chair(103,70,90,true)}${chair(63,96,180,true)}${coffee(62,57)}`:`${sofa(true)}${chair(113,30,90,true)}${chair(113,55,90,true)}${chair(113,80,90,true)}${chair(51,97,180,true)}${chair(82,97,180,true)}${coffee(63,46)}${coffee(63,72)}`;
 return `<svg class="furniture-thumbnail" data-furniture-tier="${level}" viewBox="0 0 128 112" aria-hidden="true"><rect x="1" y="1" width="126" height="110" rx="16" fill="#f1e5cb"/>${level>=2?`<g transform="translate(0 112) scale(1 -1)">${art}</g>`:art}</svg>`;
}
export function tableUpgradePreview(g:Simulation,index:number){const level=g.b.tableLevels[index],next=Math.min(3,level+1);return `<div class="furniture-upgrade-preview"><div>${furnitureThumbnail(level)}<small>${t(TABLE_TYPES[level].name)}</small></div><span aria-hidden="true">→</span><div>${furnitureThumbnail(next)}<small>${t(TABLE_TYPES[next].name)}</small></div></div>`;}
export function tableTypesPanel(g:Simulation){return `<section class="table-types"><a class="space-jump" href="#floor-investments">${t('Alan genişlet veya yeni masa ekle')} ↓</a><h3>${t('Masa türleri')}</h3><p class="sheet-intro">${t('Bistrodan koltuk grubuna, L koltuktan salon grubuna geç. Her yeni tür daha fazla misafir ve daha rahat oturma sunar.')}</p><div class="capacity-overview">${icon('chair')}<strong>${t('Toplam kapasite')}: ${g.seatingCapacity}</strong></div><div class="table-type-list">${Array.from({length:g.b.level.table},(_,i)=>{const level=g.b.tableLevels[i],current=TABLE_TYPES[level],next=TABLE_TYPES[level+1];return `<article class="table-type-card"><div class="table-type-heading">${furnitureThumbnail(level)}<div><h3>${t('Masa')} ${i+1} · ${t(current.name)}</h3><strong>${current.seats} ${t('kişilik')}</strong><small class="table-comfort">${t('Rahatlık / ek sabır')}: +${g.tableComfort(i)}s</small></div></div>${next?`<div class="furniture-next">${furnitureThumbnail(level+1)}<div><small>${t('Sonraki oturma grubu')}</small><strong>${t(next.name)}</strong></div></div><p>${t('Koltuk')}: ${current.seats} → ${next.seats} ${t('koltuk')} · ${t('Rahatlık / ek sabır')}: +${g.tableComfort(i)}s → +${next.comfort}s</p><p class="comfort-explainer">${t('Rahat oturma müşterinin sabrını ve değerlendirmesini iyileştirir.')}</p>${next.space>g.b.level.space?`<p class="table-space-required">${t('Gereken alan seviyesi')}: ${next.space} · ${t('Mevcut')}: ${g.b.level.space}</p><button class="link-button" data-review-kind="upgrade" data-review-id="space">${t('Önce kafeyi genişlet')}</button>`:''}<button class="primary" data-review-kind="table-type" data-review-id="${i}">${t('Masa değişimini incele')} · ${money(g.tableUpgradePrice(i))}</button>`:`<p class="investment-effect">${t('En rahat salon grubu')}</p>`}</article>`;}).join('')}</div></section>`;}

export function reviewsPanel(g:Simulation){return `<div class="note"><h3>${icon('star')} ${decimal(g.b.rating)} / 5 · ${number(g.b.reviewCount)} ${t('Değerlendirme')}</h3><p>${t('Puan yükseldikçe daha çok misafir gelir. 4 yıldızın üzerinde talep daha hızlı artar; masa, stok ve çalışanlarını buna göre büyüt.')}</p><strong>${t('Puana bağlı müşteri talebi')}: ${Math.round(g.reputationDemand*100)}%</strong></div><div class="review-list">${g.b.reviews.length?g.b.reviews.slice(-12).reverse().map(r=>`<article class="guest-review"><div><strong>${t(PERSONAS[r.persona].name)}</strong><span class="review-stars" aria-label="${r.score} / 5">${'★'.repeat(r.score)}${'☆'.repeat(5-r.score)}</span></div><p>${r.reasons.map(reason=>t(REASONS[reason])).join(' · ')}</p><small>${t(PERSONAS[r.persona].hint)}</small></article>`).join(''):`<p>${t('İlk misafirin ayrıldığında değerlendirmesi burada görünür.')}</p>`}</div><details class="persona-guide"><summary>${t('Misafirleri tanı')}</summary>${Object.values(PERSONAS).map(p=>`<p><strong>${t(p.name)}</strong><br>${t(p.description)}</p>`).join('')}</details><button data-invest="decor" class="primary">${t('Ortamı geliştir')}</button>`;}
export function musicPanel(g:Simulation){const b=g.b;return `<p class="sheet-intro">${t('Müzik sosyal misafirleri mutlu eder. Sessizlik arayanlar düşük sesi sever.')}</p><div class="segments music-modes">${(['off','playlist','live'] as const).map((mode,i)=>`<button data-music-mode="${mode}" aria-pressed="${b.musicMode===mode}" class="${b.musicMode===mode?'active':''}" ${mode==='playlist'&&!b.level.speakers||mode==='live'&&!b.level.stage?'disabled':''}>${t(['Kapalı','Çalma listesi','Canlı müzik'][i])}</button>`).join('')}</div><p class="sheet-intro">${t('Müzik için ses sistemi, canlı müzik için sahne gerekir.')}</p><h3>${t('Kafedeki ses düzeyi')}</h3><div class="segments">${[0,1,2,3].map((v)=>`<button data-volume="${v}" aria-pressed="${b.volume===v}" class="${b.volume===v?'active':''}">${t(['Sessiz','Düşük','Orta','Yüksek'][v])}</button>`).join('')}</div><div class="noise-summary"><p>${t('İçerideki gürültü')}: <strong>${Math.round(g.indoorNoise*100)} / 100</strong></p><p>${t('Dışarı taşan ses')}: <strong>${Math.round(g.outsideNoise*100)} / 100</strong></p><meter min="0" max="100" low="40" high="62" optimum="20" value="${g.outsideNoise*100}" aria-label="${t('Dışarı taşan ses')}"></meter></div><div class="note ${b.warningSeconds>0?'noise-warning':''}"><h3>${t(b.warningSeconds>0?'Komşulardan şikâyet var':g.outsideNoise>.62?'Komşular rahatsız olmaya başladı':'Komşularla uyumlu')}</h3><p>${t('Dışarı taşan ses 62 puanı uzun süre aşarsa polis önce uyarır. 30 saniye içinde sesi kıs veya yalıtım yap; aksi hâlde oyun altını cezası gelir.')}</p>${b.warningSeconds>0?`<strong>${t('Kalan süre')}: ${Math.ceil(b.warningSeconds)}s</strong><button class="primary" data-quiet-now>${t('Sesi hemen kıs')}</button>`:''}</div>${b.lastFine>0?`<p>${t('Son ceza')}: ${money(b.lastFine)} · ${t('Toplam ceza')}: ${money(b.totalFines)}</p>`:''}<button data-invest="decor" class="primary">${t('Ses sistemi, sahne ve yalıtım')}</button><p class="sheet-intro">${t('Düşük ses güvenli bir başlangıçtır. Yalıtım, yüksek sesin tüm misafirleri rahatsız etmesini engellemez.')}</p>`;}
export function helpPanel(){return `<p class="sheet-intro">${t('Önce bir masaya misafir oturur, sonra siparişi hazırlanır. Servis yaptığında ödeme otomatik gelir.')}</p><div class="help-stations">${[['menu','Menü','Ürünleri burada açıp kapatırsın. Aynı anda birden fazla ürün satabilirsin.'],['coffee','Hazırlık tezgâhı','Siparişleri hazırlamak için makinenin yanında dur. Hazır ürünü otomatik alırsın.'],['box','Depo','Çekirdek, süt ve tatlı malzemelerini buradan alıp hazırlık tezgâhına taşı.'],['clean','Yıkama alanı','Boş masayı temizle, kirli fincanları lavaboda yıka. Temizlikçi ve bulaşıkçı bu işleri devralabilir.']].map(([i,title,copy])=>`<div>${icon(i)}<p><strong>${t(title)}</strong><br>${t(copy)}</p></div>`).join('')}</div><div class="note"><h3>${t('Hareket ve kamera')}</h3><p>${t('Yürümek için zemine dokun veya çubuğu sürükle. İki parmağı sağa sola sürükleyerek döndür; açıp kapatarak yakınlaştır. Bilgisayarda fareyle sürükle, tekerlekle yakınlaştır.')}</p></div><p class="sheet-intro">${t('Yıldıza dokun: misafir puanlarını ve nedenlerini gör.')}</p><button class="primary" data-help-done>${t('Kafeyi açalım')}</button><button class="link-button" data-help-done>${t('Biliyorum, geç')}</button>`;}
