import {LIFETIME_BONUS} from '../game/monetization';
import {t,number} from '../game/i18n';
import type {PurchaseState} from '../platform/purchases';
import {icon} from '../view/icons';
export function noAdsPanel(state:PurchaseState){
 const price=state.price.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
 const busy=['loading','opening','verifying'].includes(state.status);
 const statuses:Record<string,string>={owned:'Tam sürüm paketi etkin.',pending:'Ödeme bekleniyor. Google Play tamamlayınca özellik açılır.',verifying:'Satın alma doğrulanıyor…',opening:'Google Play ödeme ekranı açılıyor…',loading:'Google Play kontrol ediliyor…',cancelled:'Satın alma iptal edildi. Ücretli özellik açılmadı.',verification_failed:'Satın alma henüz doğrulanamadı. Geri yüklemeyi tekrar dene.',revoked:'Bu satın alma artık etkin değil.',not_owned:'Bu Google Play hesabında önceki satın alma bulunamadı.',price_changed:'Google Play fiyatı güncellendi. Devam etmeden yeni fiyatı kontrol et.'};
 return `<div class="premium-hero">${icon('coffee')}<h3>${t('Kafenin tam sürümü.')}</h3><strong>${icon('coin')} +${number(LIFETIME_BONUS)} ${t('Altın')}</strong><p>${t('Tek seferlik satın alma. Abonelik değildir.')}</p></div><ul class="project-effects"><li>${t('Ödüllü videolar dahil tüm reklamlar ömür boyu kaldırılır.')}</li><li>${t('Çevrimdışı kafe yöneticisi açılır: sen yokken ekibin çalışmaya devam eder.')}</li><li>${t('Yatırım, bahşiş ve ekip enerjisi ödüllerini video izlemeden alırsın.')}</li><li>${t('Altın hediyesi yalnızca bir kez, ilk etkinleştirdiğin cihazdaki kafene verilir.')}</li></ul><p class="sheet-intro">${t('Altın desteği 60 saniyede, bahşiş desteği 120 saniyede bir alınabilir. Ekip enerjisi 2 dakika sürer; etkisi bitince yeniden alınabilir. Reklam gerekmez.')}</p><p class="purchase-status" role="status">${t(statuses[state.status]??(state.canPurchase?'Tek seferlik satın alma. Abonelik değildir.':'Google Play satın alımı şu anda kullanılamıyor. Oynamaya devam edebilirsin.'))}</p><button data-noads-action="buy" class="primary" ${state.canPurchase&&!busy?'':'disabled'}>${state.owned?t('Etkin'):price?`${t('Google Play ile satın al')} · ${price}`:t('Şu anda kullanılamıyor')}</button><button data-noads-action="restore" class="link-button" ${busy?'disabled':''}>${t('Satın almayı geri yükle')}</button><p class="sheet-intro">${t('Aynı Google Play hesabıyla paketini geri yükleyebilirsin. Altın hediyesi tekrar verilmez; kafe ilerlemen cihazında tutulur.')}</p><button data-panel="staff" class="link-button">${t('Ekibimi gör')}</button>`;
}

export function diamondsPanel(state:import('../platform/purchases').DiamondStoreState,balance:number){
 const busy=['loading','opening','verifying'].includes(state.status);
 const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
 const status=state.status==='pending'?'Ödeme bekleniyor. Google Play tamamlayınca özellik açılır.':state.status==='verifying'?'Satın alma doğrulanıyor…':state.status==='opening'?'Google Play ödeme ekranı açılıyor…':state.status==='price_changed'?'Google Play fiyatı güncellendi. Devam etmeden yeni fiyatı kontrol et.':state.status==='cancelled'?'Satın alma iptal edildi. Ücretli özellik açılmadı.':state.status==='error'||state.status==='verification_failed'?'Satın alma henüz doğrulanamadı. Geri yüklemeyi tekrar dene.':state.status==='unavailable'?'Google Play satın alımı şu anda kullanılamıyor. Oynamaya devam edebilirsin.':'';
 return `<div class="diamond-balance">${icon('diamond')}<strong>${number(balance)}</strong><span>${t('Elmas')}</span></div><p class="sheet-intro">${t('Elmaslarını ürün ve geliştirmeleri açmak için kullan. Altınla geliştirme seçeneğin de devam eder.')}</p><div class="diamond-packs">${state.products.map(p=>`<article class="diamond-pack"><div>${icon('diamond')}<h3>${number(p.amount)} ${t('Elmas')}</h3></div><button class="primary" data-diamond-pack="${p.productId}" ${busy||!p.canPurchase?'disabled':''}>${p.price?`${t('Satın al')} · ${escape(p.price)}`:t('Google Play fiyatı bekleniyor')}</button></article>`).join('')}</div><p class="purchase-status" role="status">${t(status)}</p><button class="link-button" data-diamonds-refresh ${busy?'disabled':''}>${t('Satın almaları kontrol et')}</button><p class="sheet-intro">${t('Tek seferlik elmas paketleri. Abonelik değildir; her paket yeniden satın alınabilir.')}</p><p class="sheet-intro">${t('Elmaslar bu cihazdaki kaydına eklenir. Kullanılmış paketler başka cihaza geri yüklenmez; kaydını silmeden önce bunu dikkate al.')}</p>`;
}
