import {t,number} from '../game/i18n';
import {chainScore} from '../game/chain-score';
import type {Save} from '../game/sim';
import type {GamesState,GamesStatus} from '../platform/play-games';
import {icon} from '../view/icons';

const escape=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function profilePanel(state:GamesState,save:Pick<Save,'branches'>){
 const score=chainScore(save),busy=state.status==='loading',connected=state.profile.authenticated;
 const copy:Record<GamesStatus,string>={unavailable:state.native?'Google Play Games şu anda kullanılamıyor. Kafeni işletmeye devam edebilirsin.':'Google Play Games profili ve sıralama Android uygulamasında kullanılabilir.',idle:'İstersen Google Play Games profilinle bağlan.',loading:'Google Play Games ile bağlantı kuruluyor…','signed-out':'Bağlanmadan da kafeni işletmeye devam edebilirsin.',connected:'Kafenin puanını bu profille paylaşabilirsin.',submitted:'Puanın gönderildi. Sıralamada en yüksek puanın korunur.',error:'Bağlantı tamamlanamadı. İnternetini kontrol edip tekrar dene.','account-changed':'Google Play Games hesabı değişti. Paylaşmadan önce profilini yeniden bağla.'};
 return `<div class="premium-hero">${icon('coffee')}<h3>${connected?escape(state.profile.displayName??''):t('Kahve hikâyen')}</h3><strong>${number(score.total)}</strong><p>${t('Kahve zinciri puanı')}</p></div><div class="stats-grid profile-score">${[[t('Şube'),score.branches,score.branches*1_000_000],[t('Yıldız'),score.stars,score.stars*100_000],[t('Servis'),score.services,score.services*10],[t('Misafir puanı'),'',score.ratingPoints]].map(([label,count,points])=>`<div><b>${number(Number(points))}</b><span>${label}${count!==''?` · ${number(Number(count))}`:''}</span></div>`).join('')}</div><p class="sheet-intro">${t('Her şube 1.000.000, her yıldız 100.000, her servis 10 puan. İlk 10.000 servis sayılır. En az 20 servis yapan şubelerin müşteri puanı en fazla 500 puan ekler.')}</p><p class="sheet-intro">${t('Altın ve elmas doğrudan puan vermez. Bu, kafe ilerlemesini karşılaştıran ödülsüz bir sıralamadır.')}</p><p class="purchase-status" role="status" aria-live="polite">${t(copy[state.status])}</p>${connected?`<button class="primary" data-games="share" ${busy?'disabled':''}>${t('Puanımı bu profille paylaş')}</button><button class="link-button" data-games="ranking" ${busy?'disabled':''}>${t('Genel sıralamayı gör')}</button>`:state.native?`<button class="primary" data-games="connect" ${busy?'disabled':''}>${t('Google Play Games ile bağlan')}</button>`:''}<p class="sheet-intro">${t('Paylaştığında Google Play Games adın ve en iyi puanın, Google profilinin görünürlük tercihlerine göre sıralamada gösterilir.')}</p><p class="sheet-intro">${t('Giriş yapmak kafe kaydını buluta taşımaz. Kafen ve elmas bakiyen bu cihazda kalır.')}</p><button class="link-button" data-close>${t('Kafeme dön')}</button>`;
}
